### ISSUE TITLE
Alvexcore 1.3 generates error with Alfresco 4.0.e

### ISSUE THREAD

**Issue by giangkt** [ITDSystems/alvex-2.x#1]
Hi team,

I've installed newest CE version (1.3) but Alfresco & Share could not start caused by:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alvex-orgchart' defined in URL [jar:file:/C:/Alfresco/tomcat/webapps/alfresco/WEB-INF/lib/alvex-core-repository-1.3-CE.jar!/alfresco/extension/alvex-orgchart-context.xml]: Cannot resolve reference to bean 'alvex-repo-extension-registry' while setting bean property 'extensionRegistry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alvex-repo-extension-registry' defined in URL [jar:file:/C:/Alfresco/tomcat/webapps/alfresco/WEB-INF/lib/alvex-core-repository-1.3-CE.jar!/alfresco/extension/alvex-extension-registry-context.xml]: Invocation of init method failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1325)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1086)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:281)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
    at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
    at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4135)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4630)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
    at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:563)
    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:498)
    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
    at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
    at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445)
    at org.apache.catalina.core.StandardService.start(StandardService.java:519)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:581)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

**Comment by giangkt** [comment]
Hi there!

I installed alvexcore 1.3 into Alfresco system running on MS Windows. That's why this error appears as my checking the source code: extension-registry\source\java\common\com\alvexcore\ExtensionRegistry.java line 72:

int slashIdx = fileName.lastIndexOf('/');

Should we change it into:  int slashIdx = fileName.lastIndexOf(File.separator) ?

Thanks.
GK.

**Comment by avasyukov** [comment]
Yes, you are right. Our bad. We tested server-side CE on Linux only. We discovered few Windows-specific bugs recently. Updates will be pushed asap.

**Comment by giangkt** [comment]
Thanks, Alexey. Please guide me how to build the source code on Ms. Windows. I also want to test and figure out the bugs if it has. I see the the code package is missing the build.properties file. Is that right?

GK.

**Comment by avasyukov** [comment]
These sources work fine for me. You just need classpath to be set. I have on my system:

```
   java.common.classpath.dir=${tomcat.repo.home}/lib
   java.repo.classpath.dir=${tomcat.repo.home}/webapps/alfresco/WEB-INF/lib
   java.share.classpath.dir=${tomcat.share.home}/webapps/share/WEB-INF/lib
```

You need something similar, details depend on your environment.

**Comment by giangkt** [comment]
Thanks! It works like a charm!!!

I changed a bit from File.separator to '/' for all codes and it ran well on Windows 7.
