### ISSUE TITLE
Error on page of workflow and task details.

### ISSUE THREAD

**Issue by ppllaxxa** [ITDSystems/alvex-2.x#4]
When I want see workflow details and go to "workflow-details" page I get
GET http://localhost:8080/share/page/_d41d8cd98f0b24e980998ecf8427e 500 (Internal Server Error)

**Comment by giangkt** [comment]
Hi there!

This is an error of Alfresco 4.2.a. It will be fixed on version 4.2.b.

**Comment by avasyukov** [comment]
Hello. Totally agree with @giangkt - it is a known bug of Alfresco 4.2.a, not Alvex. So, closing this issue.

**Comment by ppllaxxa** [comment]
Sorry, guys, but we installed Alfresco 4.2.b and Alvex 1.3-EE-beta2 and in result this bug is alive!

**Comment by fufler** [comment]
@ppllaxxa is it reproducible on a clean 4.2.b without Alvex installed?

**Comment by ppllaxxa** [comment]
No.

**Comment by avasyukov** [comment]
Ok. Looks strange. We should investigate it. We haven't tested Alvex on 4.2.b that much for the moment.

Reopening bug. @ppllaxxa, it would be helpful if you can post stack trace you get with this 500 error. You can find it either in browser in server response or in catalina.out log on the server.

**Comment by ppllaxxa** [comment]
Nov 08, 2012 7:24:44 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [Spring Surf Dispatcher Servlet] in context with path [/share] threw exception [Could not resolve view with name '_d41d8cd98f0b24e980998ecf8427e' in servlet with name 'Spring Surf Dispatcher Servlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name '_d41d8cd98f0b24e980998ecf8427e' in servlet with name 'Spring Surf Dispatcher Servlet'
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1029)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:817)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.alfresco.web.site.servlet.MTAuthenticationFilter.doFilter(MTAuthenticationFilter.java:74)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.alfresco.web.site.servlet.SSOAuthenticationFilter.doFilter(SSOAuthenticationFilter.java:374)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1813)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

**Comment by aviriel** [comment]
I tried to reproduce the bug on Linux and Windows, 4.2.b, alvex-1.3-ee-beta3. Everything works, the bug can't be reproduced. Will check it once again during final testing before 1.3 EE release, but now everything is ok.

**Comment by aviriel** [comment]
The bug is reproduced on Alfresco 4.2.b without Alvex. Alfresco repaired "Workflows I've Started" page in 4.2.b, but they didn't fix bugs on Workflow pages, that are shown on this page. Lets wait for 4.2.c.

**Comment by ppllaxxa** [comment]
Thank you for reply.
